### PR TITLE
JENKINS-60861 - Default configuration to Maven Central without HTTPS no longer work

### PR DESCRIPTION
**Pull request by foures**
Changing DEFAULT_REPOS from http to https.

### CODE REVIEW

**Comment by mdcorriveau** [comment]
Been looking why I had so many errors on my jenkins with the dependencies, thanks for the fix !

**Comment by foures** [comment]
You're welcome. BTW, I have open an [issue](https://issues.jenkins-ci.org/browse/JENKINS-60861) on Jenkins' JIRA in which I describe three workarounds. Two of them can be used in non-interactive mode. We deploy our Jenkins instances programmatically and we required a way to apply a workaround without any manual intervention. This might help to get things back to work while waiting for a new release of the plugin.

**Comment by mdcorriveau** [comment]
Thanks a lot, I'll use the "override" repo option you've described in the issue, fixed my problem !!!!

**Comment by foures** [comment]
I've also updated the message on the user interface properties file (for English and German).
The update to HTTPS should now be comprehensive.

**Pull request merged**
