### PR TITLE
[JENKINS-30554] Allow Artifact Deploy step

### PR DESCRIPTION
**Pull request by Brantone**
(2nd attempt at this ...)
Cleaned up white-spaces, was a bit inconsistent.
As for actually allowing the "Artifact Deploy" notifier:
It was unclear why the step was disabled, so to provide better management control, added a checkbox option to global config to specify if repo is "deployable". If no repos are found, then disables the notifier step (worth adding info/mention to plugin page).
Also: fixes bug where the repo wouldn't be listed on job config page until page has been saved and re-config shows list.

### CODE REVIEW

**Comment by Brantone** [comment]
Chance of merging?

**Comment by Brantone** [comment]
Merge? Would be quite useful.
Otherwise would be worth recommending using https://wiki.jenkins-ci.org/display/JENKINS/Nexus+Artifact+Uploader instead.

**Comment by jgangemi** [comment]
howdy - are you still interested in seeing this merged? if yes, can you please rebase your request? thanks!

**Comment by Brantone** [comment]
Yup, will take a look

**Comment by jgangemi** [comment]
i just merged in #21, so hopefully you didn't start on this yet. if you did, sorry.

**Comment by jgangemi** [comment]
ahh - so now that i've fully wrapped my head around this, is this even still necessary given the other plugin exists? i'm happy to support it (i actually started on a plugin to do something w/ local artifact version resolution that should probably be better off merged here) but i'm curious to know why it was disabled in the first place.

i was unable to find anything in the commit history, @imod can you offer any insight here?

**Comment by imod** [comment]
@jgangemi as far as I can remember, it was just not properly tested yet

**Comment by Brantone** [comment]
I was starting to re-visit this a while back, but sadly got pulled into other projects so haven't had a chance to touch this. I _may_ be doing some more in the future, but that remains up in the air.

**Comment by jgangemi** [comment]
resolved by #43

**Pull request closed without merging**
