### PR TITLE
Add checkbox to enable or disable LATEST/RELEASE default versions per repo

### PR DESCRIPTION
**Pull request by ovevang**
We have some internal repos where LATEST and RELEASE do not make sense as version values, so they only added noise to our deployment version dropdowns. I added a setting for this in the plugin.

### CODE REVIEW

**Comment by ovevang** [comment]
One problem is that this will modify behaviour for existing repos when upgrading the plugin. Maybe I should "reverse" the boolean so that users actively have to turn the functionality off?

**Comment by jgangemi** [comment]
agreed - you should have to explicitly enable the checkbox to remove those two values.

**Comment by ovevang** [comment]
Yes, the new version has the booleans switched around as discussed. Now you need to enable the checkbox to remove the special versions.

**Comment by jgangemi** [comment]
closing, resolved in #43

**Pull request closed without merging**
