### PR TITLE
Fix LATEST/RELEASE Version

### PR DESCRIPTION
**Pull request by fabdouglas**
Fix LATEST/RELEASE Version during all build.
For sample, after LATEST is selected, if during the build there is another version pushed into the repository. The "LATEST" will no refers to the same version.
This PR associate the LATEST/RELEASE tag to the version at this moment.

Basically, this PR store in the HTML select the version corresponding to LATEST/RELEASE.
In addition, the true version will be stored in the property. This makes possible to use this real version name for another build steps like releasing a version from its name instead of an ambiguous "LATEST".

### CODE REVIEW

**Comment by imod** [comment]
@fabdouglas any way we can test this?

**Comment by fabdouglas** [comment]
Well this is in production by my side for 1 year now ... :)
To test this plugin, simply echo the version proprety from a shell plugin. Without this PR, the version is "LATEST". With this PR, the version would be the real resolved LATEST version when you displayed the UI select such as "1.2.3"
Also, to test the fix of this PR, you can  do this :
- release a version (2.0.0)
- display the Jenkins page, the select shows [LATEST, 2.0.0, 1.0.0,...]
- release another version (3.0.0)
- without refreshing the jenkins, select "LATEST", and starts the job --> version 3.0.0 will be used instead of 2.0.0, since Aether receives "LATEST" request and not "2.0.0"
In addition, for build management (next executed plugins), it makes relevant to propagate the real resolved version instead of ambiguous and not reusable "LATEST" string.

**Comment by imod** [comment]
I'm just not sure this is what users expect, we could also expose the resolved version as an additional `ENV` variable. That would not fix all your issues, but the one to have the version available for downstream projects

**Comment by SebastienRPOCH** [comment]
Is it possible to get the version that is transformed during the Artifact resolver ? (LATEST -> 1.8-SNAPSHOT for example)
I want to get an artifact, and then deploy it. But the problem is that I use LASTEST and RELEASE dynamic parameter and after the Artifact Resolver step, version become LATEST or RELEASE and I want the exact version that I downloaded.

**Comment by fabdouglas** [comment]
This is the exact goal of this PR. Instead of "LATEST" value, the exact resolved  version value string is set to the property.

**Comment by SebastienRPOCH** [comment]
Ah, sorry. But I don't succeed yet to get the exact resolved version.
I have my Maven Repository Artifact Parameter named distversion.
And an Artifact Resolver step with ${distversion}. -> I get during this step the good version 1.8
But in the next step, when I use ${distversion} it still gives me LATEST.

**Comment by SebastienRPOCH** [comment]
I have now the exact related version but I have a bug to get the artifact : 

GRAVE: failed to expand tokens for [Artifact com.objis.democamel:demoroutecamel:war::${distversion}]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at org.jvnet.hudson.plugins.repositoryconnector.aether.ReleasedVersionRangeResolver.getLatest(ReleasedVersionRangeResolver.java:181)
        at org.jvnet.hudson.plugins.repositoryconnector.aether.ReleasedVersionRangeResolver.resolveVersionRange(ReleasedVersionRangeResolver.java:134)
        at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:370)
        at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:544)
        at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:544)
        at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:240)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:308)
        at org.jvnet.hudson.plugins.repositoryconnector.aether.Aether.resolve(Aether.java:216)
        at org.jvnet.hudson.plugins.repositoryconnector.ArtifactResolver.download(ArtifactResolver.java:129)
        at org.jvnet.hudson.plugins.repositoryconnector.ArtifactResolver.perform(ArtifactResolver.java:100)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
        at hudson.model.Build$BuildExecution.build(Build.java:206)
        at hudson.model.Build$BuildExecution.doRun(Build.java:163)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
        at hudson.model.Run.execute(Run.java:1735)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:405)

**Comment by SebastienRPOCH** [comment]
It works when I launch the job, but when I use pipelines, LATEST/RELEASE keep their name. There is a way that this plugin can be used with pipelines ?

**Comment by SebastienRPOCH** [comment]
Does this fonctionnality will be available for pipelines ? For now it doesn't seem to work.

**Comment by SebastienRPOCH** [comment]
The way LATEST and RELEASE version get their version can't be compatible with pipeline. It should be during the bulid and note before launching it.

**Comment by imod** [comment]
@fabdouglas I now merged this PR and would really love to do a release, but in order to do that properly I also need to do an update of the parent pom to the latest version https://github.com/jenkinsci/plugin-pom
Unfortunate this sounds easier than it actually is... I'm not sure when I find time to work out the issues...

**Comment by imod** [comment]
...also aether should probably be replaced by https://maven.apache.org/resolver/maven-resolver-api/dependency-info.html

**Pull request merged**
