### PR TITLE
- refactored to support pipelines

### PR DESCRIPTION
**Pull request by jgangemi**

### CODE REVIEW

**Comment by johgr814** [comment]
@jgangemi  I try to build but get compilation error:
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/johan/scania/workspace/repository-connector-plugin/src/main/java/org/jvnet/hudson/plugins/repositoryconnector/ArtifactDeployer.java:[119,33] constructor Artifact in class org.jvnet.hudson.plugins.repositoryconnector.Artifact cannot be applied to given types;
  required: java.lang.String,java.lang.String,java.lang.String
  found: java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String
  reason: actual and formal argument lists differ in length
[INFO] 1 error

**Comment by jgangemi** [comment]
@johgr814 fixed, looks like i missed a commit/push.

i'll look into hooking this up to travis to avoid this in the future.

**Comment by imod** [comment]
@jgangemi did you get my emails?

**Comment by jgangemi** [comment]
@imod now i did - it looks like gmail was marking them as spam, i'll go correct that now.

**Pull request merged**
